### ISSUE TITLE
[Publishing] Error when invoking the API for the first time

### ISSUE THREAD

**Issue by jaadds** [wso2/apim-analytics-publisher#37]
**Description:**
Following error is thrown when the first request is made

```
[2021-02-17 17:56:58,533] ERROR - APIMgtResponseHandler Cannot publish response event. Index 1 out of bounds for length 1
java.lang.ArrayIndexOutOfBoundsException: Index 1 out of bounds for length 1
        at org.wso2.carbon.apimgt.gateway.handlers.analytics.APIMgtResponseHandler.mediate_aroundBody0(APIMgtResponseHandler.java:161) [org.wso2.carbon.apimgt.gateway_6.8.210.jar:?]
        at org.wso2.carbon.apimgt.gateway.handlers.analytics.APIMgtResponseHandler.mediate(APIMgtResponseHandler.java:63) [org.wso2.carbon.apimgt.gateway_6.8.210.jar:?]
        at org.apache.synapse.mediators.ext.ClassMediator.mediate(ClassMediator.java:94) [synapse-core_2.1.7.wso2v203.jar:2.1.7-wso2v203]
        at org.apache.synapse.mediators.AbstractListMediator.mediate(AbstractListMediator.java:109) [synapse-core_2.1.7.wso2v203.jar:2.1.7-wso2v203]
        at org.apache.synapse.mediators.AbstractListMediator.mediate(AbstractListMediator.java:71) [synapse-core_2.1.7.wso2v203.jar:2.1.7-wso2v203]
        at org.apache.synapse.mediators.base.SequenceMediator.mediate(SequenceMediator.java:158) [synapse-core_2.1.7.wso2v203.jar:2.1.7-wso2v203]
        at org.apache.synapse.api.Resource.process(Resource.java:342) [synapse-core_2.1.7.wso2v203.jar:2.1.7-wso2v203]
        at org.apache.synapse.api.API.process(API.java:404) [synapse-core_2.1.7.wso2v203.jar:2.1.7-wso2v203]
        at org.apache.synapse.api.AbstractApiHandler.apiProcessNonDefaultStrategy(AbstractApiHandler.java:107) [synapse-core_2.1.7.wso2v203.jar:2.1.7-wso2v203]
        at org.apache.synapse.api.AbstractApiHandler.identifyAPI(AbstractApiHandler.java:127) [synapse-core_2.1.7.wso2v203.jar:2.1.7-wso2v203]
        at org.apache.synapse.api.AbstractApiHandler.dispatchToAPI(AbstractApiHandler.java:54) [synapse-core_2.1.7.wso2v203.jar:2.1.7-wso2v203]
        at org.apache.synapse.api.rest.RestRequestHandler.dispatchToAPI(RestRequestHandler.java:75) [synapse-core_2.1.7.wso2v203.jar:2.1.7-wso2v203]
        at org.apache.synapse.api.rest.RestRequestHandler.process(RestRequestHandler.java:54) [synapse-core_2.1.7.wso2v203.jar:2.1.7-wso2v203]
        at org.apache.synapse.rest.RESTRequestHandler.process(RESTRequestHandler.java:54) [synapse-core_2.1.7.wso2v203.jar:2.1.7-wso2v203]
        at org.apache.synapse.core.axis2.Axis2SynapseEnvironment.injectMessage(Axis2SynapseEnvironment.java:344) [synapse-core_2.1.7.wso2v203.jar:2.1.7-wso2v203]
        at org.apache.synapse.core.axis2.SynapseCallbackReceiver.handleMessage(SynapseCallbackReceiver.java:607) [synapse-core_2.1.7.wso2v203.jar:2.1.7-wso2v203]
        at org.apache.synapse.core.axis2.SynapseCallbackReceiver.receive(SynapseCallbackReceiver.java:200) [synapse-core_2.1.7.wso2v203.jar:2.1.7-wso2v203]
        at org.apache.axis2.engine.AxisEngine.receive(AxisEngine.java:180) [axis2_1.6.1.wso2v41.jar:?]
        at org.apache.synapse.transport.passthru.ClientWorker.run(ClientWorker.java:290) [synapse-nhttp-transport_2.1.7.wso2v203.jar:?]
        at org.apache.axis2.transport.base.threads.NativeWorkerPool$1.run(NativeWorkerPool.java:172) [axis2_1.6.1.wso2v41.jar:?]
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128) [?:?]
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628) [?:?]
        at java.lang.Thread.run(Thread.java:834) [?:?]
```

**Comment by tishan89** [comment]
@ruks Did we fix this?

**Comment by ruks** [comment]
Yes this is fixed
